#!/usr/bin/env sh
# gradlew - Gradle wrapper shell script (standard)

################################################################################
# DO NOT EDIT THIS FILE DIRECTLY — it's the standard Gradle wrapper script.
# If you need a different version, update gradle/wrapper/gradle-wrapper.properties
################################################################################

# Attempt to set PROJECT_DIR and GRADLE_HOME
PROGNAME="$0"

# Resolve links - $0 may be a link
while [ -h "$PROGNAME" ]; do
  ls=`ls -ld "$PROGNAME"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PROGNAME="$link"
  else
    PROGNAME=`dirname "$PROGNAME"`/"$link"
  fi
done

PRGDIR=`dirname "$PROGNAME"`
[ -z "$PRGDIR" ] && PRGDIR=.

# Use the maximum available, or set MAX_FD for old systems
MAX_FD=65536

# Ensure the wrapper jar is available
WRAPPER_JAR="$PRGDIR/gradle/wrapper/gradle-wrapper.jar"
if [ ! -f "$WRAPPER_JAR" ]; then
  echo "ERROR: gradle-wrapper.jar not found in $PRGDIR/gradle/wrapper"
  echo "Please upload 'gradle/wrapper/gradle-wrapper.jar' into the repository."
  exit 1
fi

# Set default options
DEFAULT_JVM_OPTS=""
APPEND_DEFAULT_JVM_OPTS=true

# Execute wrapper
CLASSPATH="$WRAPPER_JAR"
exec java $DEFAULT_JVM_OPTS -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
