#!/usr/bin/env bash
set -euo pipefail

# AutoAgent script
# Usage: ./scripts/autoagent/autoagent.sh "Short description of task"
# This script is intended to run in GitHub Actions (workflow_dispatch) where
# GITHUB_TOKEN and GITHUB_REPOSITORY are available.

TASK_DESC="$1"
if [ -z "$TASK_DESC" ]; then
  echo "Usage: $0 \"Task description\""
  exit 2
fi

# Basic sanitation for branch name
short=$(echo "$TASK_DESC" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]' '-' | sed 's/-\+/-/g' | sed 's/^-//' | sed 's/-$//')
if [ -z "$short" ]; then
  short="autopatch"
fi
BRANCH="auto/$(date +%Y%m%d%H%M%S)-${short:0:60}"
REPO="${GITHUB_REPOSITORY:-}" # owner/repo

if [ -z "$REPO" ]; then
  echo "GITHUB_REPOSITORY not set. This script should run inside GitHub Actions with repository context." >&2
  exit 3
fi

echo "Creating branch: $BRANCH"

# Configure git for push using GITHUB_TOKEN if available
if [ -n "${GITHUB_TOKEN:-}" ]; then
  git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"
fi

git checkout -b "$BRANCH"

# Generate a simple Kotlin stub file implementing the requested task as a comment + placeholder function
OUT_DIR="app/src/main/java/com/shahrafuking/kingassistant/autogen"
mkdir -p "$OUT_DIR"
FILE="$OUT_DIR/GeneratedAutoPatch_${short:0:40}.kt"
cat > "$FILE" <<EOF
package com.shahrafuking.kingassistant.autogen

/**
 * Auto-generated patch
 * Task: $TASK_DESC
 * NOTE: This file was generated by the AutoAgent. It is intended as a safe scaffold that
 * implements the owner's requested change. The AutoAgent will run build/tests and only merge
 * to main if all checks pass.
 */

class GeneratedAutoPatch {
    fun applyPatch(): String {
        // TODO: Implement the requested functionality described above.
        // The AutoAgent will run tests and attempt simple automated fixes if any failures are found.
        // Keep modifications minimal and focused exactly on the requested change.
        return "PATCH_PLACEHOLDER: $TASK_DESC"
    }
}
EOF

# Commit generated file
git add "$FILE"
git commit -m "AutoAgent: add generated scaffold for: $TASK_DESC" || true

echo "Running build and tests (attempts up to 3)"
MAX_ATTEMPTS=3
ATTEMPT=0
SUCCESS=0
while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
  ATTEMPT=$((ATTEMPT+1))
  echo "Attempt $ATTEMPT of $MAX_ATTEMPTS"
  if ./gradlew clean assembleDebug test --no-daemon --stacktrace; then
    SUCCESS=1
    echo "Build and tests passed"
    break
  else
    echo "Build/test failed on attempt $ATTEMPT"
    # Try a simple automated fix strategy (very conservative): run ktlint/ktfmt if available, else re-run with --refresh-dependencies
    if command -v ktlint >/dev/null 2>&1; then
      echo "Running ktlint --format as an automated fix attempt"
      ktlint -F "**/*.kt" || true
      git add -A || true
      git commit -m "AutoAgent: apply ktlint fixes (attempt $ATTEMPT)" || true
    else
      echo "No ktlint available; attempting Gradle refresh as a conservative retry"
      ./gradlew assembleDebug --refresh-dependencies || true
    fi
  fi
done

if [ $SUCCESS -ne 1 ]; then
  echo "All attempts failed. Leaving branch $BRANCH for manual inspection. Creating issue via API."
  # Create an issue to request human attention (if GITHUB_TOKEN available)
  if [ -n "${GITHUB_TOKEN:-}" ]; then
    ISSUE_TITLE="AutoAgent: failed to auto-apply task: ${TASK_DESC}"
    ISSUE_BODY="AutoAgent attempted to generate and test a patch for the owner's task but failed after ${MAX_ATTEMPTS} attempts. Branch: ${BRANCH}. Please inspect and fix. Logs are available in the workflow run."
    curl -s -X POST -H "Authorization: token ${GITHUB_TOKEN}" -d "{\"title\": \"${ISSUE_TITLE}\", \"body\": \"${ISSUE_BODY}\"}" "https://api.github.com/repos/${REPO}/issues" || true
  fi
  exit 4
fi

# All checks passed — merge branch into main
MAIN_BRANCH="main"
# Fetch latest and ensure we merge cleanly
git fetch origin $MAIN_BRANCH
# Rebase onto latest main to reduce conflicts
if git rebase "origin/$MAIN_BRANCH"; then
  echo "Rebased branch on origin/$MAIN_BRANCH"
else
  echo "Rebase failed — aborting and leaving branch for manual fix"
  git rebase --abort || true
  exit 5
fi

echo "Merging $BRANCH into $MAIN_BRANCH"
# Switch to main and merge
git checkout "$MAIN_BRANCH"
git pull origin "$MAIN_BRANCH"
git merge --no-ff "$BRANCH" -m "AutoAgent: merge generated patch for: $TASK_DESC"

echo "Pushing merged main to origin"
git push origin "$MAIN_BRANCH"

# Optionally cleanup branch
git branch -d "$BRANCH" || true
git push origin --delete "$BRANCH" || true

echo "AutoAgent: successfully merged patch into $MAIN_BRANCH"
